BlogWebProject/BlogWebProject/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ServiceProject.Models;
using ServiceProject.Services;
using ServiceProject.ViewModels;

namespace BlogWebProject.Controllers
{
    public class BlogController : BaseController
    {
        private readonly PostService _postService;
        private readonly CommentService _commentService;

        public BlogController()
        {
            _postService = new PostService();
            _commentService = new CommentService();
        }

        public IActionResult Index()
        {
            var posts = _postService.GetPosts();
            return View(posts);
        }

        public IActionResult Details(int id)
        {
            var post = _postService.GetPostById(id);

            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(PostCE_VM postViewModel)
        {
            if (ModelState.IsValid)
            {
                string userId = HttpContext.Session.GetString("UserSession");
                if (string.IsNullOrEmpty(userId))
                {
                    TempData["Mesaj"] = "Kullanıcı oturum açmamış";
                    return RedirectToAction(nameof(Index));
                }

                int newUserId = int.Parse(userId);

                _postService.CreatePost(postViewModel, newUserId);
                return RedirectToAction(nameof(Index));
            }

            return View(postViewModel);
        }

        public IActionResult Edit(int id)
        {
            string userId = HttpContext.Session.GetString("UserSession");
            if (string.IsNullOrEmpty(userId))
            {
                TempData["Mesaj"] = "Kullanıcı oturum açmamış";
                return RedirectToAction(nameof(Index));
            }

            int newUserId = int.Parse(userId);

            var post = _postService.GetPostById(id);
            if (post == null || post.UserId != newUserId)
            {
                TempData["Mesaj"] = "Bu işlemi yapmaya yetkiniz yok";
                return RedirectToAction(nameof(Index));
            }

            var postViewModel = new PostCE_VM
            {
                Id = post.Id,
                Title = post.Title,
                Content = post.Content
            };

            return View(postViewModel);
        }

        [HttpPost]
        public IActionResult Edit(int id, PostCE_VM postViewModel)
        {
            string userId = HttpContext.Session.GetString("UserSession");
            if (string.IsNullOrEmpty(userId))
            {
                TempData["Mesaj"] = "Kullanıcı oturum açmamış";
                return RedirectToAction(nameof(Index));
            }

            int newUserId = int.Parse(userId);

            var post = _postService.GetPostById(id);
            if (post == null || post.UserId != newUserId)
            {
                TempData["Mesaj"] = "Bu işlemi yapmaya yetkiniz yok";
                return RedirectToAction(nameof(Index));
            }

            if (ModelState.IsValid)
            {
                _postService.UpdatePost(id, postViewModel);
                return RedirectToAction(nameof(Index));
            }

            return View(postViewModel);
        }

        public IActionResult Delete(int id)
        {
            string userId = HttpContext.Session.GetString("UserSession");
            if (string.IsNullOrEmpty(userId))
            {
                TempData["Mesaj"] = "Kullanıcı oturum açmamış";
                return RedirectToAction(nameof(Index));
            }

            int newUserId = int.Parse(userId);

            var post = _postService.GetPostById(id);
            if (post == null || post.UserId != newUserId)
            {
                TempData["Mesaj"] = "Bu işlemi yapmaya yetkiniz yok";
                return RedirectToAction(nameof(Index));
            }

            return View(post);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            string userId = HttpContext.Session.GetString("UserSession");
            if (string.IsNullOrEmpty(userId))
            {
                TempData["Mesaj"] = "Kullanıcı oturum açmamış";
                return RedirectToAction(nameof(Index));
            }

            int newUserId = int.Parse(userId);

            var post = _postService.GetPostById(id);
            if (post == null || post.UserId != newUserId)
            {
                TempData["Mesaj"] = "Bu işlemi yapmaya yetkiniz yok";
                return RedirectToAction(nameof(Index));
            }

            _postService.DeletePost(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

BlogWebProject/BlogWebProject/Views/Blog/Create.cshtml
@model ServiceProject.ViewModels.PostCE_VM

<head>
    <link rel="stylesheet" href="~/css/create.css" />
</head>

<h1>Create New</h1>

<h4>Post</h4>

@using (Html.BeginForm("Create", "Blog", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.Title)
        @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Title)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Content)
        @Html.TextAreaFor(model => model.Content, new { @class = "form-control", @rows = 10, @cols = 50 })
        @Html.ValidationMessageFor(model => model.Content)
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
    </div>
}

BlogWebProject/BlogWebProject/Views/Blog/Delete.cshtml
@model ServiceProject.ViewModels.PostVM

@{
    ViewData["Title"] = "Delete";
}

<head>
    <link rel="stylesheet" href="~/css/delete.css" />
</head>

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="content">
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BlogWebProject/BlogWebProject/Views/Blog/Details.cshtml
@model ServiceProject.ViewModels.PostVM

@{
    ViewData["Title"] = "Details";
}

<head>
    <link rel="stylesheet" href="~/css/details.css" />
</head>

<h1>Details</h1>

<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            Posted By
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="content">
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
<div>
    <h4>Comments</h4>
    <hr />
    @if (Model.CommentCount > 0)
    {
        <p>There are @Model.CommentCount comment(s) for this post.</p>
        <a href="@Url.Action("Index","Comment", new { postId = Model.Id })" class="btn btn-primary">View Comments</a>
    }
    else
    {
        <p>No comments available for this post.</p>
    }
</div>
<a href="@Url.Action("Create", "Comment", new { postId = Model.Id })" class="btn btn-primary">Add Comment</a>

BlogWebProject/BlogWebProject/Views/Blog/Edit.cshtml
@model ServiceProject.ViewModels.PostCE_VM

@{
    ViewData["Title"] = "Edit";
}

<head>
    <link rel="stylesheet" href="~/css/edit.css" />
</head>


<h4>Edit Post</h4>

@using (Html.BeginForm("Edit", "Blog", FormMethod.Post))
{

    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Title)
        @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Title)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Content)
        @Html.TextAreaFor(model => model.Content, new { @class = "form-control", @rows = 10, @cols = 50 })
        @Html.ValidationMessageFor(model => model.Content)
    </div>

    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
        @Html.ActionLink("Cancel", "Index", new { id = Model.Id }, new { @class = "btn btn-default" })
    </div>
}

BlogWebProject/BlogWebProject/Views/Blog/Index.cshtml
@model IEnumerable<ServiceProject.ViewModels.PostVM>

@{
    ViewData["Title"] = "Blogs";
}

<head>
    <link rel="stylesheet" href="~/css/blog.css" />
</head>

<h1>Blogs</h1>

@if (TempData["Mesaj"] != null)
{
    <div class="alert alert-info">
        @TempData["Mesaj"]
    </div>
}


<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CommentCount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CommentCount)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>